# Generated by Django 4.0.3 on 2023-07-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_automobilevo_color_automobilevo_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='model',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
