# Generated by Django 4.0.3 on 2023-07-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_automobilevo_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='manufacturer',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='price',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
