# Generated by Django 4.0.3 on 2023-07-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_automobilevo_manufacturer_automobilevo_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='model',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='price',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='year',
        ),
    ]
