# Generated by Django 4.0.3 on 2023-07-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_appointment_status_alter_appointment_technician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
